version: '3.4'
# Set up all services
services:
  # First the AspNet Core app
  webapplication1:
    ## Get the image to use and set the container name
    image: webapplication1
    container_name: webapplication1

    # State a dependancy on Redis working
    depends_on:
      - "redis_image"

    # Location of the Dockerfile
    build:
      context: ./WebApplication1
      dockerfile: Dockerfile
    ports:
      - "9000:443"
      - "9001:80"

    # Configure a link to Redis
    links:
      - "redis_image"

    # The Application needs a connection string for Redis, this just needs to be the Redis Service name as defined below
    # Pass it in as an Environmental Variable
    #environment:
      #- RedisConnection=redis_image

  # The Redis Service, this label is required for the "Links" and Connection string
  redis_image:
    # Pull the image from Docker Hub
    image: redis

    # Give the container a name (any name you want)
    container_name: redis

    # Set access ports for localhost on the left
    ports:
      - "6379:6379"

   